version: '3'
services:
  cora-docker-fedora:
    image: "cora-docker-fedora:3.8.1"
    restart: always
    ports:
      - 8088:8088
      - 8443:8443
      - 61616:61616
  cora-docker-postgresql:
    image: "cora-docker-postgresql:9.6"
    restart: always
    environment:
      # same values as in files/install.properties
      POSTGRES_DB: fedora38
      POSTGRES_USER: fedoraAdmin
      POSTGRES_PASSWORD: fedora